version: "3"

# -p 8010 == OUTSIDE PARAM

#docker run --rm -it -p 8010:8000 -v /Users/letsgooo/PycharmProjects/online_store_2023/src/:/store/src --name store_app store_image bash ./commands/run_server.sh

#docker exec -it store_app bash

services:
  backend:
    build: ./
    container_name: online_store_container
    working_dir: /store
    ports:
      - 8010:8000
    command: sh -c "python /src/manage.py migrate && python /src/manage.py runserver 0:8000"
    volumes:
      - ./src:/src
      - ./commands:/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5433:5433
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5100:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pg_data: { }
  pgadmin_data: { }
