# Generated by Django 4.1.7 on 2023-03-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "photo1",
                    models.ImageField(blank=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo2",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo3",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo4",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo5",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo6",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                ("title", models.CharField(max_length=120)),
                ("characteristic", models.TextField(blank=True, max_length=1024)),
                ("status", models.CharField(default="SOLD OUT", max_length=120)),
            ],
            options={
                "verbose_name": "Archive",
                "verbose_name_plural": "All Archive",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Other", max_length=30)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "All Category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "photo1",
                    models.ImageField(blank=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo2",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo3",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo4",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo5",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                (
                    "photo6",
                    models.ImageField(blank=True, null=True, upload_to="static/img/%(class)s"),
                ),
                ("title", models.CharField(max_length=120)),
                ("size", models.CharField(default="*", max_length=5)),
                (
                    "width",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "depth",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("characteristic", models.TextField(blank=True, max_length=1024)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "All Products",
            },
        ),
    ]
