# Generated by Django 4.1.7 on 2023-07-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_archive_photo1_alter_archive_photo2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="photo1",
            field=models.ImageField(blank=True, upload_to="img"),
        ),
        migrations.AlterField(
            model_name="archive",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
        migrations.AlterField(
            model_name="archive",
            name="photo3",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo1",
            field=models.ImageField(blank=True, upload_to="img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo3",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
