# Generated by Django 4.1.7 on 2023-04-18 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_order_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
